jupyterhub:
  prePuller:
    continuous:
      enabled: false
  singleuser:
    lifecycleHooks:
      postStart:
        exec:
          command: ["rsync", "/etc/default-home-contents/", "/home/jovyan"]
          #command: ["gitpuller", "https://github.com/spacetelescope/jupyterhub-user-content", "roman-sit", "."]
    extraEnv:
      CRDS_PATH: /home/jovyan/crds_cache
      CRDS_SERVER_URL: https://jwst-serverless.stsci.edu
      CRDS_S3_ENABLED: "1"
      CRDS_S3_RETURN_URI: "0"
      CRDS_MAPPING_URI: "s3://dmd-test-crds/mappings/jwst"
      CRDS_REFERENCE_URI: "s3://dmd-test-crds/references/jwst"
      CRDS_CONFIG_URI: "s3://dmd-test-crds/config/jwst"
      CRDS_USE_PICKLES: "0"
      CRDS_DOWNLOAD_MODE: plugin
      CRDS_DOWNLOAD_PLUGIN: 'crds_s3_get ${SOURCE_URL} ${OUTPUT_PATH} ${FILE_SIZE} ${FILE_SHA1SUM}'
    defaultUrl: "/lab"
    memory:
      guarantee: 512M
      limit: 1G
  hub:
    extraConfig:
      jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']
  proxy:
    https:
      enabled: true
      type: offload
      hosts: roman-sit.science.stsci.edu
    service:
      type: LoadBalancer
      ports:
        - port: 443
          #targetPort: 
      annotations:
        # certificate ARN
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:162808325377:certificate/87c54f63-7980-4c0d-9d20-4b17756cef8a"
        # the protocol to use on the backend, we use TCP since we're using websockets
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
        # which ports should use SSL
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
  auth:
    type: custom
    custom:
      className: oauthenticator.generic.GenericOAuthenticator
      config:
        login_service: "MAST"
        token_url: "https://auth.mast.stsci.edu/oauth/access_token"
        oauth_callback_url: "https://roman-sit.science.stsci.edu/hub/oauth_login"
        userdata_method: GET
    users:
      - cslocum
      - yuvi
      - gough
    admin:
      users:
        - cslocum
