# Use this  CRDS config,  maybe with a different S3 bucket, for scalable performance on AWS.
# Optionally set CRDS_S3_RETURN_URL="1" to do direct-to-cal-memory CRDS transfers.
# CRDS_PATH: "/home/jovyan/crds_cache"
# CRDS_SERVER_URL: "https://jwst-serverless.stsci.edu"
# CRDS_S3_ENABLED: "1"
# CRDS_S3_RETURN_URI: "0"
# CRDS_MAPPING_URI: "s3://dmd-test-crds/mappings/jwst"
# CRDS_REFERENCE_URI: "s3://dmd-test-crds/references/jwst"
# CRDS_CONFIG_URI: "s3://dmd-test-crds/config/jwst"
# CRDS_USE_PICKLES: "0"
# CRDS_DOWNLOAD_MODE: plugin
# CRDS_DOWNLOAD_PLUGIN: "crds_s3_get ${SOURCE_URL} ${OUTPUT_PATH} ${FILE_SIZE} ${FILE_SHA1SUM}"

jupyterhub:
  hub:
    extraConfig:
      templates: |
        ## Configure JupyterHub to look for the templates we inject with a ConfigMap
        c.JupyterHub.template_paths.insert(0, "/etc/jupyterhub/templates")
      tike: |
        #c.Spawner.default_url = "/lab/tree/tike_content/content/Introduction.md"
        ## This works, but by setting the default notebook directory, users can't navigate to
        ## their home directory, meaning any files they create will wind up in the repo clone
        #c.Spawner.notebook_dir = "/home/jovyan/tike_content"
    extraVolumes:
      ## Make the hub pod be able to access a ConfigMap volume
      - name: hub-templates
        configMap:
          name: hub-templates
    extraVolumeMounts:
      ## Make the hub pod hub container mount that ConfigMap volume
      - mountPath: /etc/jupyterhub/templates
        name: hub-templates
  prePuller:
    continuous:
      enabled: true
  singleuser:
    image:
      tag: latest
      pullPolicy: Always
    profileList:
      - display_name: "TIKE Science Platform"
        default: true
    storage:
      dynamic:
        storageClass: "aws-efs"
    lifecycleHooks:
      postStart:
        exec:
          command:
            - "sh"
            - "-c"
            - >
              rsync -r /etc/default-home-contents/ /home/jovyan;
              gitpuller https://github.com/spacetelescope/tike_content master /home/jovyan/tike_content
    extraEnv:
      CRDS_PATH:  /home/jovyan/crds_cache
      CRDS_SERVER_URL: https://jwst-crds.stsci.edu
    defaultUrl: "/lab"
    memory:
      guarantee: 4G
      limit: 10G
  cull:
    enabled: true
    timeout: 1800
    every: 60
