apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preloaded-fits
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
  storageClassName: aws-efs
