# Base environment, with various jupyter components installed
channels:
  - manics
  - conda-forge
  - http://ssb.stsci.edu/astroconda
dependencies:
  # FIXME: Pin these somehow?
  - jupyterlab
  - nodejs
  - nb_conda_kernels
  - jupyterhub
  # For Jupyter Desktop Proxy
  - websockify==0.9.0
  - ds9==7.4
  - pip
  - pip:
    - nbgitpuller
    - git+https://github.com/jupyterhub/jupyter-server-proxy@4b5ec52
    - jupyter-desktop-server==0.1.2
