# Base environment, with various jupyter components installed
channels:
  - manics
  - conda-forge
  - http://ssb.stsci.edu/astroconda
dependencies:
  # FIXME: Pin these somehow?
  - jupyterlab
  - nodejs
  - nb_conda_kernels
  - jupyterhub
  - nbgitpuller
  # For Jupyter Desktop Proxy
  - websockify==0.9.0
  - ds9==7.4
  - pip
  - pip:
    - nbgitpuller
    - git+https://github.com/yuvipanda/jupyter-desktop-server@daecbdbbf89003a1d71fa03f362682a886bb3ad7
