jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 1
  singleuser:
    image:
      tag: latest-prod
  prePuller:
    continuous:
      # Don't need continuous pre-puller on staging
      enabled: true
