jupyterhub:
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 1
  singleuser:
    image:
      tag: latest-test
  prePuller:
    continuous:
      enabled: true 
  scheduling:
    userPlaceholder:
      enabled: true
      replicas: 1
