channels:
  #- manics
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - jupyterlab_widgets
  - ipywidgets
  - ipydatawidgets
  - ipywidgets
  - ipykernel
  - ipyvuetify
  - cfitsio
  - jupyterhub
  - nodejs
  - ipykernel
  - ipyevents
  # For Jupyter Desktop Proxy
  - websockify==0.9.0
  - pip
  - pip:
    - jupyterlab==3.1.0
    - jupyter-server-proxy
    - nbgitpuller
    - ipyvuetify>=1.4.1
    - git+https://github.com/yuvipanda/jupyter-desktop-server
    # BELOW: these shouldn't need to be here...
    - ipysplitpanes==0.1.0
    - ipygoldenlayout==0.3.0
