channels:
  - manics
  - conda-forge
  - http://ssb.stsci.edu/astroconda
dependencies:
  - cfitsio
  - jupyterhub
  - nodejs
  - ipykernel
  - ipyevents
  # For Jupyter Desktop Proxy
  - websockify==0.9.0
  - pip
  - pip:
    - jupyterlab_widgets
    - jupyterlab==3.0.11
    - jupyter-server-proxy
    - nbgitpuller
    - ipyvuetify>=1.4.1
    #- git+https://github.com/yuvipanda/jupyter-desktop-server@daecbdbbf89003a1d71fa03f362682a886bb3ad7
    - git+https://github.com/yuvipanda/jupyter-desktop-server

#  - nb_conda_kernels
#  - nb_conda
