jupyterhub:
  singleuser:
    lifecycleHooks:
      postStart:
        exec:
          command: ["cp", "-afr", "/etc/default-home-contents", "/home/jovyan"]
    defaultUrl: "/lab"
    memory:
      guarantee: 512M
      limit: 1G
  proxy:
    https:
      enabled: false
