# Base environment, with various jupyter components installed
channels:
  - manics
  - conda-forge
  - http://ssb.stsci.edu/astroconda
dependencies:
  # FIXME: Pin these somehow?
  - setuptools==42
  - jupyterlab
  - nodejs
  - nb_conda_kernels
  - jupyterhub
  - jupyter-rsession-proxy
  - nbgitpuller
  # For Jupyter Desktop Proxy
  - websockify==0.9.0
  - ds9==7.4
